// Consolidated language data for both recognition and translation
export const languages = {
  // Recognition languages (with country codes for better accuracy)
  recognition: {
    'af-ZA': 'Afrikaans',
    'am-ET': 'Amharic',
    'az-AZ': 'Azerbaijani',
    'bn-BD': 'Bengali (Bangladesh)',
    'bn-IN': 'Bengali (India)',
    'id-ID': 'Indonesian',
    'ms-MY': 'Malay',
    'ca-ES': 'Catalan',
    'cs-CZ': 'Czech',
    'da-DK': 'Danish',
    'de-DE': 'German',
    'en-AU': 'English (Australia)',
    'en-CA': 'English (Canada)',
    'en-IN': 'English (India)',
    'en-KE': 'English (Kenya)',
    'en-TZ': 'English (Tanzania)',
    'en-GH': 'English (Ghana)',
    'en-NZ': 'English (New Zealand)',
    'en-NG': 'English (Nigeria)',
    'en-ZA': 'English (South Africa)',
    'en-PH': 'English (Philippines)',
    'en-GB': 'English (United Kingdom)',
    'en-US': 'English (United States)',
    'es-AR': 'Spanish (Argentina)',
    'es-BO': 'Spanish (Bolivia)',
    'es-CL': 'Spanish (Chile)',
    'es-CO': 'Spanish (Colombia)',
    'es-CR': 'Spanish (Costa Rica)',
    'es-EC': 'Spanish (Ecuador)',
    'es-SV': 'Spanish (El Salvador)',
    'es-ES': 'Spanish (Spain)',
    'es-US': 'Spanish (United States)',
    'es-GT': 'Spanish (Guatemala)',
    'es-HN': 'Spanish (Honduras)',
    'es-MX': 'Spanish (Mexico)',
    'es-NI': 'Spanish (Nicaragua)',
    'es-PA': 'Spanish (Panama)',
    'es-PY': 'Spanish (Paraguay)',
    'es-PE': 'Spanish (Peru)',
    'es-PR': 'Spanish (Puerto Rico)',
    'es-DO': 'Spanish (Dominican Republic)',
    'es-UY': 'Spanish (Uruguay)',
    'es-VE': 'Spanish (Venezuela)',
    'eu-ES': 'Basque',
    'fil-PH': 'Filipino',
    'fr-FR': 'French',
    'jv-ID': 'Javanese',
    'gl-ES': 'Galician',
    'gu-IN': 'Gujarati',
    'hr-HR': 'Croatian',
    'zu-ZA': 'Zulu',
    'is-IS': 'Icelandic',
    'it-IT': 'Italian (Italy)',
    'it-CH': 'Italian (Switzerland)',
    'kn-IN': 'Kannada',
    'km-KH': 'Khmer',
    'lv-LV': 'Latvian',
    'lt-LT': 'Lithuanian',
    'ml-IN': 'Malayalam',
    'mr-IN': 'Marathi',
    'hu-HU': 'Hungarian',
    'lo-LA': 'Lao',
    'nl-NL': 'Dutch',
    'ne-NP': 'Nepali',
    'nb-NO': 'Norwegian Bokmål',
    'pl-PL': 'Polish',
    'pt-BR': 'Portuguese (Brazil)',
    'pt-PT': 'Portuguese (Portugal)',
    'ro-RO': 'Romanian',
    'si-LK': 'Sinhala',
    'sl-SI': 'Slovenian',
    'su-ID': 'Sundanese',
    'sk-SK': 'Slovak',
    'fi-FI': 'Finnish',
    'sv-SE': 'Swedish',
    'sw-TZ': 'Swahili (Tanzania)',
    'sw-KE': 'Swahili (Kenya)',
    'ka-GE': 'Georgian',
    'hy-AM': 'Armenian',
    'ta-IN': 'Tamil (India)',
    'ta-SG': 'Tamil (Singapore)',
    'ta-LK': 'Tamil (Sri Lanka)',
    'ta-MY': 'Tamil (Malaysia)',
    'te-IN': 'Telugu',
    'vi-VN': 'Vietnamese',
    'tr-TR': 'Turkish',
    'ur-PK': 'Urdu (Pakistan)',
    'ur-IN': 'Urdu (India)',
    'el-GR': 'Greek',
    'bg-BG': 'Bulgarian',
    'ru-RU': 'Russian',
    'sr-RS': 'Serbian',
    'uk-UA': 'Ukrainian',
    'ko-KR': 'Korean',
    'cmn-Hans-CN': 'Chinese (Mandarin, Simplified, China)',
    'cmn-Hans-HK': 'Chinese (Mandarin, Simplified, Hong Kong)',
    'cmn-Hant-TW': 'Chinese (Traditional, Taiwan)',
    'yue-Hant-HK': 'Chinese (Cantonese, Traditional, Hong Kong)',
    'ja-JP': 'Japanese',
    'hi-IN': 'Hindi',
    'th-TH': 'Thai'
  },
  
  // Translation languages (simplified BCP 47 tags)
  translation: {
    'af': 'Afrikaans',
    'am': 'Amharic',
    'az': 'Azerbaijani',
    'bn': 'Bengali',
    'id': 'Indonesian',
    'ms': 'Malay',
    'ca': 'Catalan',
    'cs': 'Czech',
    'da': 'Danish',
    'de': 'German',
    'en-US': 'English',
    'es': 'Spanish',
    'eu': 'Basque',
    'fil': 'Filipino',
    'fr': 'French',
    'jv': 'Javanese',
    'gl': 'Galician',
    'gu': 'Gujarati',
    'hr': 'Croatian',
    'zu': 'Zulu',
    'is': 'Icelandic',
    'it': 'Italian',
    'kn': 'Kannada',
    'km': 'Khmer',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'ml': 'Malayalam',
    'mr': 'Marathi',
    'hu': 'Hungarian',
    'lo': 'Lao',
    'nl': 'Dutch',
    'ne': 'Nepali',
    'nb': 'Norwegian Bokmål',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'si': 'Sinhala',
    'sl': 'Slovenian',
    'su': 'Sundanese',
    'sk': 'Slovak',
    'fi': 'Finnish',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ka': 'Georgian',
    'hy': 'Armenian',
    'ta': 'Tamil',
    'te': 'Telugu',
    'vi': 'Vietnamese',
    'tr': 'Turkish',
    'ur': 'Urdu',
    'el': 'Greek',
    'bg': 'Bulgarian',
    'ru': 'Russian',
    'sr': 'Serbian',
    'uk': 'Ukrainian',
    'ko': 'Korean',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'hi': 'Hindi',
    'th': 'Thai'
  }
};

// Helper function to get language options for select elements
export function getLanguageOptions(type) {
  const langData = languages[type];
  return Object.entries(langData).map(([code, name]) => ({
    value: code,
    text: name
  }));
}
